#!/usr/bin/env bash
# AetherProxy one-shot install script
# Usage: curl -fsSL https://raw.githubusercontent.com/amirreza225/AetherProxy/main/deploy/install.sh | bash
set -euo pipefail

REPO_URL="https://github.com/amirreza225/AetherProxy.git"
INSTALL_DIR="${AETHER_INSTALL_DIR:-/opt/aetherproxy}"
COMPOSE_FILE="$INSTALL_DIR/deploy/docker-compose.yml"
ENV_FILE="$INSTALL_DIR/deploy/.env"

# ── Prerequisites ────────────────────────────────────────────────────────────
require() {
  command -v "$1" >/dev/null 2>&1 || { echo "ERROR: $1 is required but not installed."; exit 1; }
}
require git
require docker

# ── Clone / update ───────────────────────────────────────────────────────────
if [ -d "$INSTALL_DIR/.git" ]; then
  echo "Updating existing installation at $INSTALL_DIR …"
  git -C "$INSTALL_DIR" pull --ff-only
else
  echo "Cloning AetherProxy into $INSTALL_DIR …"
  git clone --depth=1 "$REPO_URL" "$INSTALL_DIR"
fi

# ── Generate .env if it doesn't exist ────────────────────────────────────────
if [ ! -f "$ENV_FILE" ]; then
  echo "Generating $ENV_FILE …"
  JWT_SECRET=$(openssl rand -hex 32)
  cat > "$ENV_FILE" <<EOF
# Auto-generated by install.sh — edit before going to production
AETHER_JWT_SECRET=$JWT_SECRET
AETHER_ADMIN_ORIGIN=https://panel.example.com
NEXT_PUBLIC_API_URL=https://api.example.com
PANEL_DOMAIN=panel.example.com
API_DOMAIN=api.example.com
EOF
  echo ""
  echo "⚠  Edit $ENV_FILE and set your real domains before starting."
  echo ""
fi

# ── Start services ────────────────────────────────────────────────────────────
echo "Starting AetherProxy …"
docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d --build

echo ""
echo "✅  AetherProxy is running."
echo "   Admin panel : https://\$PANEL_DOMAIN"
echo "   API server  : https://\$API_DOMAIN"
